services:
  kali:
    image: agnusdei1207/kali:latest
    container_name: kali
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    network_mode: host
    volumes:
      - kali-volume:/data
      - ./vpn:/vpn
    environment:
      - DISPLAY=:0
    privileged: true
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "1194:1194/udp"
      - "1337:1337/udp"
      - "21:21"
      - "22:22"
      - "80:80"
      - "443:443/udp"
      - "445:445"
      - "139:139"
      - "8080:8080"
    command: sleep infinity

  postgres:
    image: postgres:latest
    container_name: kali-postgres
    environment:
      POSTGRES_DB: kali
      POSTGRES_USER: kali
      POSTGRES_PASSWORD: kali
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  kali-volume:
    name: kali-volume
  postgres-volume:
    name: postgres-volume
