services:
  oscp:
    image: agnusdei1207/oscp:latest
    container_name: oscp
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    network_mode: host
    volumes:
      - oscp-volume:/data
      - ./vpn:/vpn
    privileged: true
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "1194:1194/udp"
      - "1337:1337/udp"
      - "21:21"
      - "22:22"
      - "80:80"
      - "443:443/udp"
      - "445:445"
      - "139:139"
      - "8080:8080"
    command: sleep infinity

  ai:
    image: ollama/ollama
    container_name: ai
    platform: linux/amd64
    volumes:
      - ai-volume:/data
    ports:
      - "11434:11434"
    cmd: ["ollama", "run", "deepseek-r1:1.5b"]

volumes:
  oscp-volume:
    name: oscp-volume
  ai-volume:
    name: ai-volume
